-- SQL Schema for Supabase - Laundry Management System

-- 1. Bảng Cơ sở (Branches)
CREATE TABLE IF NOT EXISTS branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  "adminId" BIGINT DEFAULT 1
);

-- 2. Bảng Người dùng (Users)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'staff',
  name TEXT,
  "branchId" BIGINT,
  "branchIds" TEXT DEFAULT '[]',
  "salaryType" TEXT DEFAULT 'parttime',
  "salaryRate" BIGINT DEFAULT 0,
  "adminId" BIGINT DEFAULT 1
);

-- 3. Bảng Dịch vụ (Services)
CREATE TABLE IF NOT EXISTS services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price BIGINT DEFAULT 0,
  unit TEXT,
  category TEXT,
  "adminId" BIGINT DEFAULT 1
);

-- 4. Bảng Khách hàng (Customers)
CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT UNIQUE NOT NULL,
  name TEXT,
  "adminId" BIGINT DEFAULT 1
);

-- 5. Bảng Đơn hàng (Orders)
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  staff TEXT,
  "customerName" TEXT,
  "customerPhone" TEXT,
  service TEXT,
  weight REAL,
  "pricePerKg" BIGINT DEFAULT 0,
  surcharge BIGINT DEFAULT 0,
  discount BIGINT DEFAULT 0,
  "totalPrice" BIGINT DEFAULT 0,
  "paymentStatus" TEXT DEFAULT 'Chưa thanh toán',
  "paymentMethod" TEXT DEFAULT 'Tiền mặt',
  status TEXT DEFAULT 'Đang xử lý',
  "returnDate" TIMESTAMP WITH TIME ZONE,
  "paidAt" TIMESTAMP WITH TIME ZONE,
  note TEXT,
  "branchId" BIGINT,
  "isHidden" SMALLINT DEFAULT 0,
  "adminId" BIGINT DEFAULT 1
);

-- 6. Bảng Ca làm việc (Shifts)
CREATE TABLE IF NOT EXISTS shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staffId" BIGINT,
  "branchId" BIGINT,
  date TEXT,
  "startTime" TEXT,
  "endTime" TEXT,
  "actualStartTime" TEXT,
  "actualEndTime" TEXT,
  status TEXT DEFAULT 'Pending',
  "shiftName" TEXT,
  "adminId" BIGINT DEFAULT 1
);

-- 7. Bảng Mẫu ca làm việc (Shift Templates)
CREATE TABLE IF NOT EXISTS shift_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  "startTime" TEXT,
  "endTime" TEXT,
  "adminId" BIGINT DEFAULT 1
);

-- 8. Bảng Báo cáo doanh thu (Daily Reports)
CREATE TABLE IF NOT EXISTS daily_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id BIGINT,
  report_date TEXT,
  opening_balance BIGINT DEFAULT 0,
  expense_amount BIGINT DEFAULT 0,
  expense_desc TEXT,
  notes TEXT,
  "adminid" BIGINT DEFAULT 1
);

-- CHÈN TÀI KHOẢN ADMIN MẶC ĐỊNH
INSERT INTO users (email, password, role, name, "adminId")
VALUES ('admin@test.com', '123', 'admin', 'Chủ Tiệm', 1)
ON CONFLICT (email) DO NOTHING;
